#!/usr/bin/env bash
#this script display bad luck in 4th loop and good look in 8th loop
i=0
while (( i++ < 10 ))
do
if [ $i -eq 4 ]
then 
echo "bad luck"
elif [ $i -eq 8 ]
then 
	echo "good luck"
else	
	echo "Best School" 
fi
done 
