#!/usr/bin/env bash
#this script display bad luck in 4th loop and good look in 8th loop
i=0
while (( i++ > 10 ))
do 
echo "Best School" 
if [ $i -eq 4 ]
then 
echo "bad luck"
elif [ $i -eq 8 ]
then 
echo "good luck"
continue 
fi 
done 
