#!/usr/bin/env bash
# this scrpt display bad luck from China, Japan and Italy
i=0
while (( i=i+1 ))
do
	echo "$i"
case $i in
4) 
echo "bad luck from China";; 
9)
echo "bad luck from Japan";; 
17)
echo "bad luck from Italy";;
20) exit;;
esac 
done 
