#!/usr/bin/env bash
#This script check if the files exist, are empty or if are regulars files.

if [[ -f school ]]
then 
	echo "school file exist"
else 
	echo "school files does not exist"

	if [[ -s school ]]
	then
		echo "school file is empty"
	else 
		echo "school file is not empty"

		if [[ -d school ]]
		then 
			echo "school is a regular file"
		fi
	fi
fi

