#!/usr/bin/env bash
#This script don't love u.
touch /var/run/myscript.pid
trap 'echo Y U no love me?!' SIGINT
	trap 'rm  /var/run/myscript.pid' SIGQUIT SIGTERM
trap 'echo I hate the kill command' SIGTERM

while true 
do
echo 'To infinity and beyond'
sleep 2
done 
