#!/usr/bin/env bash
#This script don't love u.
touch /var/run/myscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?! "' 2
trap "rm  /var/run/myscript.pid" 3 15	

while true 
	do
echo 'To infinity and beyond'
sleep 2
done 
