#!/usr/bin/env bash
#This script start, stop and restarts the process in manage_my_process.

case "$1" in 

start)
echo "manage_my_process started"
touch /var/run/my_process.pid 
  echo $! > /var/run/my_process.pid
./manage_my_process "$1"
  ;;

stop) 
	echo "manage_my_process stopped"
	kill -9 "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
;;

restart) 
echo "manage_my_process restarted"
kill -9 "$(cat /var/run/my_process.pid)"
rm /var/run/my_process.pid
touch /var/run/my_process.pid
echo $! > /var/run/my_process.pid
./manage_my_process "$1"
;;

*)
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac 
