#!/usr/bin/env bash
#This script start, stop and restarts the process in manage_my_process.

case "$1" in 
start)
touch /var/run/my_process.pid 
echo "manage_my_process started"
./manage_my_process
;;
stop) 
pkill -|f "/var/run/my_process.pid"
rm /var/run/my_process.pid
echo "manage_my_process stopped"
;;
restart) 
rm /var/run/my_process.pid
echo "manage_my_process restarted"
;;
esac 
